changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking-changes

    - title: Bug Fixes
      labels:
        - bug

    - title: Improvements
      labels:
        - enhancement

    - title: Other Changes
      labels:
        - "*"
