name: Releases

on: 
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          generateReleaseNotes: true